FROM mcr.microsoft.com/dotnet/core/sdk:2.2.300-alpine3.9 AS builder

# Set the working directory
WORKDIR /root

# Create directories for all project files
RUN mkdir -p ./WordFlip.Data ./WordFlip.Services ./WordFlip.WebApi

# Copy the the project files
COPY ./src/WordFlip.Data/WordFlip.Data.csproj ./WordFlip.Data
COPY ./src/WordFlip.Services/WordFlip.Services.csproj ./WordFlip.Services
COPY ./src/WordFlip.WebApi/WordFlip.WebApi.csproj ./WordFlip.WebApi

# Restore the dependencies of the project
RUN dotnet restore ./WordFlip.WebApi/WordFlip.WebApi.csproj

# Copy the rest of the source files
COPY ./src .

# Rename the Docker-specific API settings file to its default name
RUN mv ./WordFlip.WebApi/appsettings.Docker.json ./WordFlip.WebApi/appsettings.json

# Build and deploy the application
RUN dotnet publish ./WordFlip.WebApi/WordFlip.WebApi.csproj -c release -o ../publish



FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.5-alpine3.9

WORKDIR /root
COPY --from=builder /root/publish .
ENV ASPNETCORE_URLS=http://+:8080
#ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 8080

# Start the web API service
ENTRYPOINT ["dotnet", "./WordFlip.WebApi.dll"]