FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y


# In production, make sure to change to a secure password after running the container!
# Don't forget to change the login details in ./setup-database.sh accordingly.
# /opt/mssql-tools/bin/sqlcmd -U SA -P 'OLD_PASSWORD' -Q 'ALTER LOGIN SA WITH PASSWORD="NEW_PASSWORD"'
ENV SA_PASSWORD=January2018

# In production, make sure to use a server that requires a license:
# * Standard
# * Enterprise

#ENV MSSQL_PID=Developer
ENV MSSQL_PID=Express

WORKDIR /src

# Copy the database setup scripts
COPY setup-database.sql ./
COPY boot-database.sh ./
COPY setup-database.sh ./

# Grant permissions for the setup scripts to be executable
#USER root
#RUN chmod +x ./boot-database.sh
#RUN chmod +x ./setup-database.sh

ENTRYPOINT bash ./boot-database.sh