version: "3"
services:
    api:
        build:
          context: .
          dockerfile: Dockerfile-api
        image: word-flip-api:1.0
        container_name: api
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        build:
          context: .
          dockerfile: Dockerfile-db
        image: word-flip-api-db:1.0
        container_name: db